name: Run shell.py Manually

# Allows manual triggering via GitHub UI "Run workflow" button
on:
  workflow_dispatch:

jobs:
  run-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'  # pick your Python version

      - name: Install dependencies (if you have any)
        run: |
          python -m pip install --upgrade pip
          # If you have requirements.txt, uncomment next line:
          # pip install -r requirements.txt
      - run: pip install -r requirements.txt

      - name: Run shell.py script
        run: python path/to/shell.py

